### ISSUE TITLE
New user accounts unable to complete account confirmation process

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1534]
Any attempt to confirm a new account caused an unexpected error response on the web site. The site logs:

```
18:52:25.414 [http-nio-8080-exec-10] ERROR c.p.c.c.CloudSessionLocalUserService - Json syntace service error
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(
true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.parallax.client.cloudsession.CloudSessionLocalUserService.doConfirm(CloudSessionLocalUserServic
e.java:244)
        at com.parallax.server.blocklyprop.servlets.ConfirmServlet.confirmToken(ConfirmServlet.java:94)
        at com.parallax.server.blocklyprop.servlets.ConfirmServlet.doGet(ConfirmServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
...
```

**Comment by zfi** [comment]
Two root causes to this one. My development system was using the master branch of the cloud-session-java-client while the Demo and production systems were using the 1.2 branch of that repository.

Second, in the 1.2 branch, a change was introduced to replace repeated uri strings with constants. During the refactoring, one uri without a training '/' was replaced with the constant, which did contain a trailing '/'. That broke access to the /local/confirm endpoint.

A patch was submitted in PR #1535 to correct the error.
