### ISSUE TITLE
Unnecessary stack trace logging in CloudSessionAuthenticationRealm class

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#945]
The  CloudSessionAuthenticationRealm.doGetAuthenticationInfo method is dumping stack traces into the log file when it encounters expected exceptions. Suggest that the method log the error with a specific message and move on. 

```
CloudSessionAuthenticationRealm [CloudSessionAuthenticationRealm.java:81] Unknown user
com.parallax.client.cloudsession.exceptions.UnknownUserException: Unknown user
        at com.parallax.client.cloudsession.CloudSessionAuthenticateService.authenticateLocalUser(CloudSessionAuthenticateService.java:63)
        at com.parallax.server.blocklyprop.services.impl.SecurityServiceImpl.authenticateLocalUser(SecurityServiceImpl.java:108)
        at com.adamlewis.guice.persist.jooq.JdbcLocalTxnInterceptor.invoke(JdbcLocalTxnInterceptor.java:63)
        at com.parallax.server.blocklyprop.services.impl.SecurityServiceImpl.authenticateLocalUserStatic(SecurityServiceImpl.java:98)
       ...
```

**Comment by zfi** [comment]
Updated code to treat an unknown user as a login failure mode and return a corresponding error code to the caller. This change eliminated the uncaught UnknownUserException at issue here.
